[book]
authors = ["kiarie404"]
language = "en"   # The main language of the book, which is used as a language attribute <html lang="en">
multilingual = false
src = "src"
title = "MFI Expert User Guide"

#  A description for the book, which is added as meta information in the html <head> of each page
description = "MFI Expert user Documentation and Guide"
some_unique_variable = "ha ha ha"


[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding

[output.html]
theme = "theme"
default-theme = "Navy"
preferred-dark-theme = "Navy"

